# Author: PeiwenJi
# Date created: 2021.4.24
# Name: MainUI.py 
# Description: Program main interface


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1369, 852)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        Main.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAuthor = QtWidgets.QLabel(self.centralwidget)
        self.lblAuthor.setGeometry(QtCore.QRect(530, 780, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setItalic(True)
        self.lblAuthor.setFont(font)
        self.lblAuthor.setProperty("color", QtGui.QColor(141, 141, 141))
        self.lblAuthor.setObjectName("lblAuthor")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 40, 1071, 691))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.btFile = QtWidgets.QPushButton(self.centralwidget)
        self.btFile.setGeometry(QtCore.QRect(10, 230, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btFile.setFont(font)
        self.btFile.setObjectName("btFile")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 300, 181, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.rbtCos = QtWidgets.QRadioButton(self.groupBox)
        self.rbtCos.setGeometry(QtCore.QRect(20, 30, 132, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rbtCos.setFont(font)
        self.rbtCos.setObjectName("rbtCos")
        self.rbtSin = QtWidgets.QRadioButton(self.groupBox)
        self.rbtSin.setGeometry(QtCore.QRect(20, 60, 132, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rbtSin.setFont(font)
        self.rbtSin.setObjectName("rbtSin")
        self.rbtTan = QtWidgets.QRadioButton(self.groupBox)
        self.rbtTan.setGeometry(QtCore.QRect(20, 90, 132, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rbtTan.setFont(font)
        self.rbtTan.setObjectName("rbtTan")
        self.rbtDiff = QtWidgets.QRadioButton(self.groupBox)
        self.rbtDiff.setGeometry(QtCore.QRect(20, 120, 132, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.rbtDiff.setFont(font)
        self.rbtDiff.setObjectName("rbtDiff")
        self.edtFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.edtFilePath.setGeometry(QtCore.QRect(70, 230, 171, 31))
        self.edtFilePath.setObjectName("edtFilePath")
        self.btDraw = QtWidgets.QPushButton(self.centralwidget)
        self.btDraw.setGeometry(QtCore.QRect(50, 490, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btDraw.setFont(font)
        self.btDraw.setObjectName("btDraw")
        Main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionCos = QtWidgets.QAction(Main)
        self.actionCos.setObjectName("actionCos")
        self.actionSin = QtWidgets.QAction(Main)
        self.actionSin.setObjectName("actionSin")
        self.actionDifferentiation = QtWidgets.QAction(Main)
        self.actionDifferentiation.setObjectName("actionDifferentiation")
        self.actionIntegrate = QtWidgets.QAction(Main)
        self.actionIntegrate.setObjectName("actionIntegrate")
        self.actionOpen = QtWidgets.QAction(Main)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Main)
        self.actionSave.setObjectName("actionSave")
        self.actionZoomIn = QtWidgets.QAction(Main)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(Main)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionretract = QtWidgets.QAction(Main)
        self.actionretract.setObjectName("actionretract")
        self.actionExtend = QtWidgets.QAction(Main)
        self.actionExtend.setObjectName("actionExtend")
        self.actionRetract = QtWidgets.QAction(Main)
        self.actionRetract.setObjectName("actionRetract")
        self.action2 = QtWidgets.QAction(Main)
        self.action2.setObjectName("action2")
        self.action4 = QtWidgets.QAction(Main)
        self.action4.setObjectName("action4")
        self.action0_25 = QtWidgets.QAction(Main)
        self.action0_25.setObjectName("action0_25")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.lblAuthor.setText(_translate("Main", "© PeiwenJi, Sichuan University"))
        self.btFile.setText(_translate("Main", "File"))
        self.groupBox.setTitle(_translate("Main", "Transformation"))
        self.rbtCos.setText(_translate("Main", "cos"))
        self.rbtSin.setText(_translate("Main", "sin"))
        self.rbtTan.setText(_translate("Main", "tan"))
        self.rbtDiff.setText(_translate("Main", "difference"))
        self.btDraw.setText(_translate("Main", "Draw"))
        self.actionCos.setText(_translate("Main", "Cos"))
        self.actionSin.setText(_translate("Main", "Sin"))
        self.actionDifferentiation.setText(_translate("Main", "Exponent"))
        self.actionIntegrate.setText(_translate("Main", "Difference"))
        self.actionOpen.setText(_translate("Main", "Open"))
        self.actionSave.setText(_translate("Main", "Save"))
        self.actionZoomIn.setText(_translate("Main", "Zoom in"))
        self.actionZoomOut.setText(_translate("Main", "Zoom out"))
        self.actionretract.setText(_translate("Main", "Retract"))
        self.actionExtend.setText(_translate("Main", "0.5"))
        self.actionRetract.setText(_translate("Main", "1"))
        self.action2.setText(_translate("Main", "2"))
        self.action4.setText(_translate("Main", "5"))
        self.action0_25.setText(_translate("Main", "0.1"))


